
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'pAND NOT OR WORDp : t xx : OR t x\n         | t : f yy : AND f y\n         |f : NOT f\n         | WORD f\n         | WORD'
    
_lr_action_items = {'NOT':([0,4,5,7,9,],[4,4,4,4,4,]),'WORD':([0,4,5,7,9,],[5,5,5,5,5,]),'$end':([1,2,3,5,6,8,10,11,12,13,14,15,],[0,-3,-6,-9,-1,-4,-7,-8,-3,-6,-2,-5,]),'OR':([2,3,5,8,10,11,12,13,15,],[7,-6,-9,-4,-7,-8,7,-6,-5,]),'AND':([3,5,10,11,13,],[9,-9,-7,-8,9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'p':([0,],[1,]),'t':([0,7,],[2,12,]),'f':([0,4,5,7,9,],[3,10,11,3,13,]),'x':([2,12,],[6,14,]),'y':([3,13,],[8,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> p","S'",1,None,None,None),
  ('p -> t x','p',2,'p_p','parser.py',5),
  ('x -> OR t x','x',3,'p_x','parser.py',10),
  ('x -> <empty>','x',0,'p_x','parser.py',11),
  ('t -> f y','t',2,'p_t','parser.py',16),
  ('y -> AND f y','y',3,'p_y','parser.py',22),
  ('y -> <empty>','y',0,'p_y','parser.py',23),
  ('f -> NOT f','f',2,'p_f','parser.py',29),
  ('f -> WORD f','f',2,'p_f','parser.py',30),
  ('f -> WORD','f',1,'p_f','parser.py',31),
]
