# Generated by Django 2.2.12 on 2022-05-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lexer', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
