# Generated by Django 2.2.12 on 2022-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('lexer', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('documents', models.TextField(default='')),
                ('frequency', models.IntegerField(default=0)),
                ('max_freq', models.IntegerField(default=0)),
            ],
        ),
    ]
