# Generated by Django 2.2.12 on 2022-05-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_djangomigrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
    ]
